name: CI

on: [push]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Build with Maven
        run: ./mvnw clean install -U

  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
    with:
      java-cache: 'maven'
      java-version: 11

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: publish release package
      if: contains( github.ref, 'master' ) || contains( github.base_ref, 'master' )
      env:
        JENKINS_MAVEN_PASS: ${{ secrets.JENKINS_MAVEN_PASS }}
      run: ./mvnw -s .github/workflows/m2.settings.xml deploy -DskipTests=true
